steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "us.gcr.io/ompldr/bitcoind:$REVISION_ID", "."]
  dir: 'lightning-node/bitcoind'
- name: 'gcr.io/cloud-builders/docker'
  args: ["tag", "us.gcr.io/ompldr/bitcoind:$REVISION_ID", "us.gcr.io/ompldr/bitcoind:latest"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "us.gcr.io/ompldr/bitcoind:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "us.gcr.io/ompldr/bitcoind:latest"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - patch
  - statefulset
  - bitcoind
  - --type=json
  - '-p=[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"us.gcr.io/ompldr/bitcoind:$REVISION_ID"}]'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ompldr-us-east4'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - patch
  - statefulset
  - bitcoind
  - --type=json
  - '-p=[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"us.gcr.io/ompldr/bitcoind:$REVISION_ID"}]'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ompldr-us-west1'
